name: cppcheck
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install cppcheck
        run: sudo apt-get -y install cppcheck
      - name: Cppcheck code
        run: cppcheck banking.cc
